<?php

$title = 'Blog';
$this->headTitle($title);

?>

<h1>
    <?= $this->escapeHtml($title) ?>
</h1>

<p>
    <a href="<?= $this->url('blog', ['action' => 'create']) ?>">
        Add post
    </a>
</p>

<table class="table">
    <thead>
        <th>Title</th>
        <th>Description</th>
        <th>Action</th>
    </thead>
    <tbody>
    <?php foreach ($blogs as $blog) : ?>
    <tr>
        <td> <?= $this->escapeHtml($blog->title) ?> </td>
        <td> <?= $this->escapeHtml($blog->description) ?> </td>
        <td>
            <a href="<?= $this->url('blog', ['action' => 'update', 'id' => $blog->id]) ?>">Edit</a>
            <a href="<?= $this->url('blog', ['action' => 'delete', 'id' => $blog->id]) ?>">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>

</table>